/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp3.simulacion;
import javax.swing.*;
import java.math.*;

/**
 *
 * @author Juaco
 */
public class Inicio extends javax.swing.JPanel {

    private String botonSeleccionado;
    public Inicio() {
        initComponents();
        this.jPanel_Param_Exp.setVisible(false);
        this.jPanel_Param_Unif.setVisible(false);
        this.jPanel_Param_Normal.setVisible(false);
        
    }
    public void generarValoresDistUniforme(int paramA, int paramB, int cantVal)
    {
        double random=Math.random();
        double nuevoRandom ;
        int a = paramA;
        int b= paramB;
        int n;
        this.jTable1.addRowSelectionInterval(0, cantVal);
        
        
        for (int i = 0; i < this.jTable1.getRowCount(); i++) {
            
            n= i+1;
            this.jTable1.setValueAt(n, i, 1);
            nuevoRandom= a + random*(b-a);
            this.jTable1.setValueAt(nuevoRandom, i, 2);
            random= Math.random();
            
        }
        
    }
    public void generarValoresDistNormal(int media, int varianza, int cantVal)
    {
        double random1= Math.random();
        double random2= Math.random();
        double z;
        double nuevoRandom;
        int n;
        
        this.jTable1.addRowSelectionInterval(0,cantVal);
        
        for (int i = 0; i < this.jTable1.getRowCount() ; i++) {
            n=i+1;
            this.jTable1.setValueAt(n, i, 1);
            z=  Math.sqrt((-2)*Math.log(random1))*Math.cos((2*Math.PI)*random2);
            nuevoRandom= media+(varianza*z);
            this.jTable1.setValueAt(nuevoRandom, i, 2);
            random1=Math.random();
            random2=Math.random();
                   
            }
     }
    public void generarValoresDistExp(int lambda, int cantVal)
    {
        double random1= Math.random();
        double nuevoRandom;
        int n;
        this.jTable1.addRowSelectionInterval(0,cantVal);
        for (int i = 0; i < cantVal; i++) {
            
            n=i+1;
            this.jTable1.setValueAt(n, i, 1);
            nuevoRandom= ((-1)/lambda)*(Math.log((1-random1)));
            this.jTable1.setValueAt(nuevoRandom, i, 2);
            random1= Math.random();
           
        }
    }
    public void generarValoresDistPoisson(int lambda, int cantVal)
    {
        int n=0;
        double a = Math.pow(Math.E, -(lambda));
        double b=1;
        double i=0;
        this.jTable1.addRowSelectionInterval(0, cantVal);
        
        for (int j = 0; j < cantVal; j++) {
            n=j+1;
            this.jTable1.setValueAt(n, j, 1);
            while(b>=a)
            {
            i++;
            b*=Math.random();
            }
            this.jTable1.setValueAt(i, j, 2);
            i=0;
            
        }
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_Uniforme = new javax.swing.JButton();
        btn_Exponencial = new javax.swing.JButton();
        btn_Poisson = new javax.swing.JButton();
        btn_Normal = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btn_generar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        Grafico = new javax.swing.JPanel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jPanel_Param_Normal = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txt_media_DistNorm = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_varianza_DistNorm = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_cantVal_Norm = new javax.swing.JTextField();
        jPanel_Param_Exp = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txt_lambda = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_cantVal_Exp = new javax.swing.JTextField();
        jPanel_Param_Unif = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_a = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_b = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_cantVal_Unif = new javax.swing.JTextField();
        jPanel_Param_Poisson = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txt_lambda_DistPoisson = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_cantVal_DistPoisson = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_cantIntervalos = new javax.swing.JTextField();

        setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 13)); // NOI18N
        jLabel1.setText("TP3 - Variables Aleatorias");

        jLabel2.setText("Seleccione la distribucion:");

        btn_Uniforme.setText("Uniforme");
        btn_Uniforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UniformeActionPerformed(evt);
            }
        });

        btn_Exponencial.setText("Exponencial");
        btn_Exponencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExponencialActionPerformed(evt);
            }
        });

        btn_Poisson.setText("Poisson");
        btn_Poisson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PoissonActionPerformed(evt);
            }
        });

        btn_Normal.setText("Normal");
        btn_Normal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NormalActionPerformed(evt);
            }
        });

        jLabel5.setText("Ingrese valores de Parametros:");

        btn_generar.setText("Generar");
        btn_generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "n", "Variables Generadas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel12.setText("Valores Generados:");

        jLabel13.setText("Grafica de la Distribucion:");
        jLabel13.setToolTipText("");

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout GraficoLayout = new javax.swing.GroupLayout(Grafico);
        Grafico.setLayout(GraficoLayout);
        GraficoLayout.setHorizontalGroup(
            GraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
        );
        GraficoLayout.setVerticalGroup(
            GraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 215, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Grafico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Grafico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jLayeredPane1.setLayer(Grafico, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLayeredPane2.setDoubleBuffered(true);

        jPanel_Param_Normal.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel_Param_Normal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("Media: ");
        jPanel_Param_Normal.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, -1));
        jPanel_Param_Normal.add(txt_media_DistNorm, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 110, -1));

        jLabel8.setText("Varianza: ");
        jPanel_Param_Normal.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, -1, -1));
        jPanel_Param_Normal.add(txt_varianza_DistNorm, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 110, -1));

        jLabel11.setText("Cantidad de Valores a Generar:");
        jPanel_Param_Normal.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 3, -1, -1));
        jPanel_Param_Normal.add(txt_cantVal_Norm, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 90, -1));

        jPanel_Param_Exp.setEnabled(false);
        jPanel_Param_Exp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Lambda: ");
        jPanel_Param_Exp.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));
        jPanel_Param_Exp.add(txt_lambda, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 90, -1));

        jLabel9.setText("Cantidad de Valores a Generar:");
        jPanel_Param_Exp.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, -1, -1));
        jPanel_Param_Exp.add(txt_cantVal_Exp, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 90, -1));

        jPanel_Param_Normal.add(jPanel_Param_Exp, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 487, 35));

        jPanel_Param_Unif.setEnabled(false);
        jPanel_Param_Unif.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("a :");
        jPanel_Param_Unif.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 3, 24, -1));
        jPanel_Param_Unif.add(txt_a, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 0, 90, -1));

        jLabel4.setText("b :");
        jPanel_Param_Unif.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 3, -1, -1));
        jPanel_Param_Unif.add(txt_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 0, 90, -1));

        jLabel10.setText("Cantidad de Valores a Generar:");
        jPanel_Param_Unif.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 8, -1, -1));
        jPanel_Param_Unif.add(txt_cantVal_Unif, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 5, 90, -1));

        jPanel_Param_Normal.add(jPanel_Param_Unif, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel15.setText("Lambda:");

        jLabel16.setText("Cantidad de Valores a Generar:");

        javax.swing.GroupLayout jPanel_Param_PoissonLayout = new javax.swing.GroupLayout(jPanel_Param_Poisson);
        jPanel_Param_Poisson.setLayout(jPanel_Param_PoissonLayout);
        jPanel_Param_PoissonLayout.setHorizontalGroup(
            jPanel_Param_PoissonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Param_PoissonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_lambda_DistPoisson, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_cantVal_DistPoisson, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(359, Short.MAX_VALUE))
        );
        jPanel_Param_PoissonLayout.setVerticalGroup(
            jPanel_Param_PoissonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Param_PoissonLayout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addGroup(jPanel_Param_PoissonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txt_lambda_DistPoisson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(txt_cantVal_DistPoisson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel_Param_Normal.add(jPanel_Param_Poisson, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, -1, -1));

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_Param_Normal, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_Param_Normal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jLayeredPane2.setLayer(jPanel_Param_Normal, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel14.setText("Cantidad Intervalos:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(394, 394, 394)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(btn_Uniforme, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Exponencial)
                            .addComponent(btn_Poisson, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Normal, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_cantIntervalos, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_generar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(170, 170, 170)
                                .addComponent(jLabel13)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel5)))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_Uniforme, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Exponencial, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Poisson, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Normal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_generar))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(txt_cantIntervalos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 13, 13)
                                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap(78, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_UniformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UniformeActionPerformed
        botonSeleccionado="U";
        this.btn_Exponencial.setVisible(false);
        this.btn_Poisson.setVisible(false);
        this.btn_Normal.setVisible(false);
        this.jPanel_Param_Unif.setVisible(true);
        this.jPanel_Param_Exp.setVisible(false);
        this.jPanel_Param_Poisson.setVisible(false);
        this.jPanel_Param_Normal.setVisible(false);
        
    
    }//GEN-LAST:event_btn_UniformeActionPerformed

    private void btn_ExponencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExponencialActionPerformed
        botonSeleccionado="E";
        this.btn_Uniforme.setVisible(false);
        this.btn_Poisson.setVisible(false);
        this.btn_Normal.setVisible(false);
        this.jPanel_Param_Unif.setVisible(false);
        this.jPanel_Param_Exp.setVisible(true);
        this.jPanel_Param_Poisson.setVisible(false);
        this.jPanel_Param_Normal.setVisible(false);
        
    }//GEN-LAST:event_btn_ExponencialActionPerformed

    private void btn_NormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NormalActionPerformed
        botonSeleccionado="N";
        this.btn_Uniforme.setVisible(false);
        this.btn_Poisson.setVisible(false);
        this.btn_Exponencial.setVisible(false);
        this.jPanel_Param_Unif.setVisible(false);
        this.jPanel_Param_Exp.setVisible(false);
        this.jPanel_Param_Poisson.setVisible(false);
        this.jPanel_Param_Normal.setVisible(true);
        
        
    }//GEN-LAST:event_btn_NormalActionPerformed

    private void btn_generarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generarActionPerformed
       // Aca se generan los datos de la tabla y tambien el grafico 
        
        switch (botonSeleccionado) {
            case "U": 
                        if(this.txt_a.getText().isEmpty()||this.txt_b.getText().isEmpty()||this.txt_cantVal_Unif.getText().isEmpty())
                        {
                        JOptionPane.showMessageDialog(this, "Falta ingresar valor (a ,b,cantidad Valores)", "Error",JOptionPane.ERROR_MESSAGE);
                        } else {
                            
                            int variableA= Integer.parseInt(this.txt_a.getText());
                            int variableB= Integer.parseInt(this.txt_b.getText());
                            int variableCantVal= Integer.parseInt(this.txt_cantVal_Unif.getText());
                            
                            this.generarValoresDistUniforme(variableA, variableB,variableCantVal);
                            
                            
        }
                break;
            case "E":
                        if(this.txt_cantVal_Exp.getText().isEmpty()||this.txt_lambda.getText().isEmpty())
                        {
                        JOptionPane.showMessageDialog(this, "Falta ingresar valor (lambda,cantidad Valores)", "Error",JOptionPane.ERROR_MESSAGE);
                        }else{
                        int varCantVal= Integer.parseInt(this.txt_cantVal_Exp.getText());
                        int varLambda= Integer.parseInt(this.txt_lambda.getText());
                        
                        this.generarValoresDistExp(varLambda, varCantVal);
                        }
                
                break;
            case "N":
                        if(this.txt_cantVal_Norm.getText().isEmpty()||this.txt_media_DistNorm.getText().isEmpty()||this.txt_varianza_DistNorm.getText().isEmpty())
                        {
                        JOptionPane.showMessageDialog(this, "Falta ingresar valor (media,varianza,cantidad Valores)", "Error",JOptionPane.ERROR_MESSAGE);
                        }else{
                        int varCantVal= Integer.parseInt(this.txt_cantVal_Norm.getText());
                        int varMedia= Integer.parseInt(this.txt_media_DistNorm.getText());
                        int varVarianza= Integer.parseInt(this.txt_varianza_DistNorm.getText());
                        
                        this.generarValoresDistNormal(varMedia, varVarianza, varCantVal);
                            
                        
                        }   
                
                break;
                
            case "P":
                        if(this.txt_lambda_DistPoisson.getText().isEmpty()||this.txt_cantVal_DistPoisson.getText().isEmpty())
                        {
                        JOptionPane.showMessageDialog(this, "Falta ingresar valor (lambda,cantidad Valores)", "Error",JOptionPane.ERROR_MESSAGE);
                        }else{
                        int varLambda= Integer.parseInt(this.txt_lambda_DistPoisson.getText());
                        int varCantVal= Integer.parseInt(this.txt_cantVal_DistPoisson.getText());
                        
                        }
            
            default:
//                throw new AssertionError();
                        JOptionPane.showMessageDialog(this,"Falta Seleccionar una Distribucion","Error",JOptionPane.ERROR_MESSAGE);
                
        }
            
    }//GEN-LAST:event_btn_generarActionPerformed

    private void btn_PoissonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PoissonActionPerformed
      
        botonSeleccionado="P";
        this.btn_Uniforme.setVisible(false);
        this.btn_Normal.setVisible(false);
        this.btn_Exponencial.setVisible(false);
        this.jPanel_Param_Unif.setVisible(false);
        this.jPanel_Param_Exp.setVisible(false);
        this.jPanel_Param_Poisson.setVisible(true);
        this.jPanel_Param_Normal.setVisible(false);
        
    }//GEN-LAST:event_btn_PoissonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Grafico;
    private javax.swing.JButton btn_Exponencial;
    private javax.swing.JButton btn_Normal;
    private javax.swing.JButton btn_Poisson;
    private javax.swing.JButton btn_Uniforme;
    private javax.swing.JButton btn_generar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel_Param_Exp;
    private javax.swing.JPanel jPanel_Param_Normal;
    private javax.swing.JPanel jPanel_Param_Poisson;
    private javax.swing.JPanel jPanel_Param_Unif;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_a;
    private javax.swing.JTextField txt_b;
    private javax.swing.JTextField txt_cantIntervalos;
    private javax.swing.JTextField txt_cantVal_DistPoisson;
    private javax.swing.JTextField txt_cantVal_Exp;
    private javax.swing.JTextField txt_cantVal_Norm;
    private javax.swing.JTextField txt_cantVal_Unif;
    private javax.swing.JTextField txt_lambda;
    private javax.swing.JTextField txt_lambda_DistPoisson;
    private javax.swing.JTextField txt_media_DistNorm;
    private javax.swing.JTextField txt_varianza_DistNorm;
    // End of variables declaration//GEN-END:variables
}
